// Mocks generated by Mockito 5.2.0 from annotations
// in todoapp/test/controller_tests/todo_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todoapp/model/todo.dart' as _i4;
import 'package:todoapp/repository/todo_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [TodosRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodosRepository extends _i1.Mock implements _i2.TodosRepository {
  @override
  _i3.Future<List<_i4.Todo>> getAll() =>
      (super.noSuchMethod(Invocation.method(#getAll, []),
              returnValue: Future<List<_i4.Todo>>.value(<_i4.Todo>[]))
          as _i3.Future<List<_i4.Todo>>);
  @override
  _i3.Future<List<_i4.Todo>> getAllProcessing() =>
      (super.noSuchMethod(Invocation.method(#getAllProcessing, []),
              returnValue: Future<List<_i4.Todo>>.value(<_i4.Todo>[]))
          as _i3.Future<List<_i4.Todo>>);
  @override
  _i3.Future<List<_i4.Todo>> getAllCompleted() =>
      (super.noSuchMethod(Invocation.method(#getAllCompleted, []),
              returnValue: Future<List<_i4.Todo>>.value(<_i4.Todo>[]))
          as _i3.Future<List<_i4.Todo>>);
  @override
  _i3.Future<bool> updateTodo(_i4.Todo? todo) =>
      (super.noSuchMethod(Invocation.method(#updateTodo, [todo]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> addTodo(_i4.Todo? todo) =>
      (super.noSuchMethod(Invocation.method(#addTodo, [todo]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> deleteTodo(_i4.Todo? todo) =>
      (super.noSuchMethod(Invocation.method(#deleteTodo, [todo]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}

/// A class which mocks [Todo].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodo extends _i1.Mock implements _i4.Todo {
  @override
  set id(int? _id) => super.noSuchMethod(Invocation.setter(#id, _id),
      returnValueForMissingStub: null);
  @override
  set title(String? _title) =>
      super.noSuchMethod(Invocation.setter(#title, _title),
          returnValueForMissingStub: null);
  @override
  set task(String? _task) => super.noSuchMethod(Invocation.setter(#task, _task),
      returnValueForMissingStub: null);
  @override
  set done(bool? _done) => super.noSuchMethod(Invocation.setter(#done, _done),
      returnValueForMissingStub: null);
  @override
  Map<String, Object?> toMap() =>
      (super.noSuchMethod(Invocation.method(#toMap, []),
          returnValue: <String, Object?>{}) as Map<String, Object?>);
}
